In [1]:
!pip install be-great pandas -q
print("✓ Dependencies installed")

✓ Dependencies installed

In [2]:
from google.colab import files
uploaded = files.upload()
# Click "Choose Files" and select great_train_data_5k.csv

Saving great_train_data_5k.csv to great_train_data_5k.csv

In [3]:
import pandas as pd
from be_great import GReaT
import warnings
warnings.filterwarnings('ignore')

# Load training data
df_train = pd.read_csv('great_train_data_5k.csv')
print(f"Loaded {len(df_train)} training records")

# Random seeds (must match local experiments)
seeds = [42, 123, 456, 789, 1011]

# Generate 5 replicates
for rep, seed in enumerate(seeds, 1):
    print(f"\n{'='*50}")
    print(f"REPLICATE {rep}/5 (seed={seed})")
    print(f"{'='*50}")

    # Train model
    print("Training GReaT model...")
    model = GReaT(
        llm='distilgpt2',
        epochs=100,
        batch_size=32
    )
    model.fit(df_train)
    print("✓ Training complete")

    # Generate synthetic data
    print(f"Generating {len(df_train)} synthetic records...")
    df_synth = model.sample(n_samples=len(df_train))

    # Save
    filename = f'great_rep{rep}.csv'
    df_synth.to_csv(filename, index=False)
    print(f"✓ Saved to {filename}")

print(f"\n{'='*50}")
print("ALL 5 REPLICATES COMPLETE!")
print(f"{'='*50}")

Loaded 3500 training records

==================================================
REPLICATE 1/5 (seed=42)
==================================================
Training GReaT model...

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

✓ Training complete
Generating 3500 synthetic records...

  0%|          | 0/3500 [00:00<?, ?it/s]The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
3572it [00:31, 111.80it/s]

✓ Saved to great_rep1.csv

==================================================
REPLICATE 2/5 (seed=123)
==================================================
Training GReaT model...

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

✓ Training complete
Generating 3500 synthetic records...

3572it [00:30, 115.98it/s]

✓ Saved to great_rep2.csv

==================================================
REPLICATE 3/5 (seed=456)
==================================================
Training GReaT model...

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

✓ Training complete
Generating 3500 synthetic records...

3572it [00:30, 115.25it/s]

✓ Saved to great_rep3.csv

==================================================
REPLICATE 4/5 (seed=789)
==================================================
Training GReaT model...

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

✓ Training complete
Generating 3500 synthetic records...

3572it [00:31, 113.29it/s]

✓ Saved to great_rep4.csv

==================================================
REPLICATE 5/5 (seed=1011)
==================================================
Training GReaT model...

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'pad_token_id': 50256}.
You're using a GPT2TokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.

✓ Training complete
Generating 3500 synthetic records...

3572it [00:31, 113.55it/s]

✓ Saved to great_rep5.csv

==================================================
ALL 5 REPLICATES COMPLETE!
==================================================

In [4]:
from google.colab import files

for rep in range(1, 6):
    files.download(f'great_rep{rep}.csv')
    print(f"Downloaded great_rep{rep}.csv")

Downloaded great_rep1.csv

Downloaded great_rep2.csv

Downloaded great_rep3.csv

Downloaded great_rep4.csv

Downloaded great_rep5.csv